### ISSUE TITLE
Error: package or namespace load failed for ‘TCGAbiolinks’

### ISSUE THREAD

**Issue by jasonyee** [BioinformaticsFMRP/TCGAbiolinks#141]
I installed the stable version of [TCGAbiolinks](https://www.bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/index.html) using `source("https://bioconductor.org/biocLite.R")` and `biocLite("TCGAbiolinks")` in RStudio.

But when I tried to using the package `library(TCGAbiolinks)` the Error occurred as
`Error: package or namespace load failed for ‘TCGAbiolinks’:
 object ‘rbind.gtable’ is not exported by 'namespace:gridExtra'`.

Can anyone help me with this issue?

Thanks

**Comment by citifun** [comment]
I have had a similar issue and have tried various ways to install  including upgrading packages from source and from binaries - but without success

> biocLite("TCGAbiolinks",type="source")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.1 (2017-06-30).
Installing package(s) ‘TCGAbiolinks’
trying URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/TCGAbiolinks_2.5.7.tar.gz'
Content type 'application/x-gzip' length 48880035 bytes (46.6 MB)
downloaded 46.6 MB

* installing *source* package 'TCGAbiolinks' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error : object 'rbind.gtable' is not exported by 'namespace:gridExtra'
ERROR: lazy loading failed for package 'TCGAbiolinks'
* removing 'C:/Users/AlanH/Documents/R/win-library/3.4/TCGAbiolinks'

The downloaded source packages are in
	‘C:\Users\AlanH\AppData\Local\Temp\RtmpIT945g\downloaded_packages’
Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\AlanH\Documents\R\win-library\3.4" C:\Users\AlanH\AppData\Local\Temp\RtmpIT945g/downloaded_packages/TCGAbiolinks_2.5.7.tar.gz' had status 1 
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘TCGAbiolinks’ had non-zero exit status

Thanks for your help

Alan

**Comment by AswathyPaul** [comment]
the function name is updated.

https://cran.r-project.org/web/packages/gridExtra/news.html

**Comment by baptiste** [comment]
yes, sorry for the inconvenience. Please use gtable_cbind / gtable_rbind instead. The previous name was inherited from gtable, but I found it awkward to import the S3 generic that had a different signature.

**Comment by citifun** [comment]
Thanks for all your efforts - gridExtra Version 2.3  gives the same error - I'm not sure where to apply  " Please use gtable_cbind / gtable_rbind "

> biocLite("TCGAbiolinks",type="source")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.1 (2017-06-30).
Installing package(s) ‘TCGAbiolinks’
trying URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/TCGAbiolinks_2.5.7.tar.gz'
Content type 'application/x-gzip' length 48880035 bytes (46.6 MB)
downloaded 46.6 MB

* installing *source* package 'TCGAbiolinks' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error : object 'rbind.gtable' is not exported by 'namespace:gridExtra'
ERROR: lazy loading failed for package 'TCGAbiolinks'
* removing 'C:/Users/AlanH/Documents/R/win-library/3.4/TCGAbiolinks'

The downloaded source packages are in
	‘C:\Users\AlanH\AppData\Local\Temp\RtmpKoj5xe\downloaded_packages’
Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\AlanH\Documents\R\win-library\3.4" C:\Users\AlanH\AppData\Local\Temp\RtmpKoj5xe/downloaded_packages/TCGAbiolinks_2.5.7.tar.gz' had status 1 
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘TCGAbiolinks’ had non-zero exit status
> packageVersion("gridExtra")
[1] ‘2.3’

**Comment by citifun** [comment]
Also a problem with an R-version 3.3.3 which can install TCGAbiolinks

> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.3                         
year           2017                        
month          03                          
day            06                          
svn rev        72310                       
language       R                           
version.string R version 3.3.3 (2017-03-06)
nickname       Another Canoe               
> library("TCGAbiolinks")
Error : object ‘rbind.gtable’ is not exported by 'namespace:gridExtra'
Error: package or namespace load failed for ‘TCGAbiolinks’
> packageVersion("gridExtra")
[1] ‘2.3’

**Comment by AswathyPaul** [comment]
gridtable 2.3 is the updated one. You can try to install older version 2.2.1. But when we try to install TCGABiolinks, it will try to update the package. If the version doesn't match with TCGABiolinks installation you wont succeed. I guess TCGABiolinks has to be updated now.

**Comment by tiagochst** [comment]
I fixed it yesterday. I didn't saw the issue was here.

**Comment by jasonyee** [comment]
@tiagochst Thanks for your effort, I really appreciate your quick response. Could you please tell me how to get the fixed version of TCGAbiolinks? 
Since I tried to use `biocLite` to update the `TCGAbiolinks`, the problem still remain.
Thank you.

**Comment by AswathyPaul** [comment]
Even I tried just now after tiagochst said it was corrected. But I have the same problem.

**Comment by tiagochst** [comment]
It should be in Bioconductor in some days. Plase, could you install from github. 
``` devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")```

**Comment by citifun** [comment]
Thanks for the comment and suggestion - problem solved!

**Comment by AswathyPaul** [comment]
Thank you @tiagochst .

**Comment by hsbori** [comment]
I should mention that this error still occurs. Installing from github works perfectly, thanks for the help!

**Comment by Patmedi** [comment]
Thank you @tiagochst, your comment was so useful!!

**Comment by echozhang77777** [comment]
@tiagochst Hello friend, I tried your code: devtools::install_github("BioinformaticsFMRP/TCGAbiolinks") to install library("TCGAbiolinks"), but it also showed I failed.  I don´t know why
