### ISSUE TITLE
TCGAbiolinks stop working

### ISSUE THREAD

**Issue by oflorez** [BioinformaticsFMRP/TCGAbiolinks#157]
Hi all -
I was running during the last couple of days TCGAbiolinks for the following command to retrieve Clinical Data: 
`clin <- GDCquery_clinic("TCGA-BLCA", type = "clinical", save.csv = TRUE)`

It worked just perfect. However, it's not working anymore. I'm getting this message:
 
`--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg38
Warning: 40 parsing failures.
row # A tibble: 5 x 5 col     row   col  expected     actual                                                        file expected   <int> <chr>     <chr>      <chr>                                                       <chr> actual 1     1  <NA> 8 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' file 2     2  <NA> 8 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' row 3     3  <NA> 8 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' col 4     4  <NA> 8 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' expected 5     5  <NA> 8 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv'
... ................. ... .............................................................................................. ........ .............................................................................................. ...... .................. [... truncated]

|disease_type.2              |disease_type.5                      |disease_type.4       |disease_type.6               |
|:---------------------------|:-----------------------------------|:--------------------|:----------------------------|
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|Thymic Epithelial Neoplasms |Complex Mixed and Stromal Neoplasms |Basal Cell Neoplasms |Ductal and Lobular Neoplasms |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
|NA                          |NA                                  |NA                   |NA                           |
Error in checkProjectInput(project) : 
  Please set a valid project argument from the column id above. Project TCGA-COAD was not found.
In addition: Warning messages:
1: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 
2: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)
3: Unknown or uninitialised column: 'project_id'. 
4: Unknown or uninitialised column: 'project_id'.`

**Comment by tiagochst** [comment]
The data from the API changed. The TSV export failed. Now it should be fixed.
Could you please update the package from github?
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by oflorez** [comment]
Many thanks - it works now. Best!

**Comment by MaisaDaoud** [comment]
I had exactly the same problem. I uninstalled R, removed all the associated folders and reinstalled it R*64 3.4.2, I used  devtools::install_github("BioinformaticsFMRP/TCGAbiolinks") but still have problems 
>>>>>>>>>>>
>devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")
Downloading GitHub repo BioinformaticsFMRP/TCGAbiolinks@master
from URL https://api.github.com/repos/BioinformaticsFMRP/TCGAbiolinks/zipball/master
Installing TCGAbiolinks
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/***/AppData/Local/Temp/Rtmpcx87x1/devtools287cc37af/BioinformaticsFMRP-TCGAbiolinks-6c6eb63"  \
  --library="C:/Program Files/R/R-3.4.2/library" --install-tests 

* installing *source* package 'TCGAbiolinks' ...
** R
** data
*** moving datasets to lazyload DB
Warning: namespace 'GenomicRanges' is not available and has been replaced
by .GlobalEnv when processing object 'dataREAD'
Warning: namespace 'GenomicRanges' is not available and has been replaced
by .GlobalEnv when processing object 'dataREAD'
Warning: namespace 'SummarizedExperiment' is not available and has been replaced
by .GlobalEnv when processing object 'gbm.exp.harmonized'
Warning: namespace 'SummarizedExperiment' is not available and has been replaced
by .GlobalEnv when processing object 'gbm.exp.harmonized'
Warning: namespace 'SummarizedExperiment' is not available and has been replaced
by .GlobalEnv when processing object 'gbm.exp.legacy'
Warning: namespace 'SummarizedExperiment' is not available and has been replaced
by .GlobalEnv when processing object 'gbm.exp.legacy'
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'GenomeInfoDbData'
ERROR: lazy loading failed for package 'TCGAbiolinks'
* removing 'C:/Program Files/R/R-3.4.2/library/TCGAbiolinks'
Installation failed: Command failed (1)
>>>>
I've been trying with it for a few days, any solutions will be highly appreciated

**Comment by tiagochst** [comment]
It says you need to install GenomeInfoDbData. I'll check the warnings.


source("https://bioconductor.org/biocLite.R")
biocLite("GenomeInfoDbData")

devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")


Tiago Chedraoui Silva

**Comment by MaisaDaoud** [comment]
Yes I did that and the problem is solved finally, thanks
