### ISSUE TITLE
Error with GDCprepare for copy number variation query (legacy = T)

### ISSUE THREAD

**Issue by JessicaCruz31** [BioinformaticsFMRP/TCGAbiolinks#285]
I am trying to use GDCprepare on a query for CNV data with legacy = T, but I get the error : 

> Error in if (query$data.type == "Gene Level Copy Number Scores") { : 
  missing value where TRUE/FALSE needed

But for the legacy archive there is no data.type for CNV data. What can I do to fix this?

This is my code:

`query.skcm2.noncnv <- GDCquery(project = "TCGA-SKCM", data.category = "Copy number variation",
                               legacy = TRUE, file.type = "nocnv_hg19.seg",
                               sample.type = c("Metastatic"), barcode = barcode2)
GDCdownload(query.skcm2.noncnv)
cnvskcm.2 <- GDCprepare(query.skcm2.noncnv, save = TRUE, save.filename = "skcm2.nocnvhg19.rda")
`
 sessionInfo()

> R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C               LC_TIME=pt_BR.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] TCGAbiolinks_2.11.2

loaded via a namespace (and not attached):
  [1] backports_1.1.3             circlize_0.4.5              aroma.light_3.12.0         
  [4] plyr_1.8.4                  selectr_0.4-1               ConsensusClusterPlus_1.46.0
  [7] lazyeval_0.2.1              splines_3.5.2               BiocParallel_1.16.5        
 [10] usethis_1.4.0               GenomeInfoDb_1.18.1         ggplot2_3.1.0              
 [13] sva_3.30.1                  digest_0.6.18               foreach_1.4.4              
 [16] magrittr_1.5                memoise_1.1.0               cluster_2.0.7-1            
 [19] doParallel_1.0.14           limma_3.38.3                remotes_2.0.2              
 [22] ComplexHeatmap_1.20.0       Biostrings_2.50.2           readr_1.3.1                
 [25] annotate_1.60.0             matrixStats_0.54.0          R.utils_2.7.0              
 [28] prettyunits_1.0.2           colorspace_1.3-2            blob_1.1.1                 
 [31] rvest_0.3.2                 ggrepel_0.8.0               xfun_0.4                   
 [34] dplyr_0.7.8                 callr_3.1.1                 crayon_1.3.4               
 [37] RCurl_1.95-4.11             jsonlite_1.6                genefilter_1.64.0          
 [40] bindr_0.1.1                 zoo_1.8-4                   survival_2.43-3            
 [43] iterators_1.0.10            glue_1.3.0                  survminer_0.4.3            
 [46] gtable_0.2.0                zlibbioc_1.28.0             XVector_0.22.0             
 [49] GetoptLong_0.1.7            DelayedArray_0.8.0          pkgbuild_1.0.2             
 [52] shape_1.4.4                 BiocGenerics_0.28.0         scales_1.0.0               
 [55] DESeq_1.34.1                DBI_1.0.0                   edgeR_3.24.3               
 [58] ggthemes_4.0.1              Rcpp_1.0.0                  xtable_1.8-3               
 [61] progress_1.2.0              cmprsk_2.2-7                bit_1.1-14                 
 [64] matlab_1.0.2                km.ci_0.5-2                 stats4_3.5.2               
 [67] httr_1.4.0                  RColorBrewer_1.1-2          pkgconfig_2.0.2            
 [70] XML_3.98-1.16               R.methodsS3_1.7.1           locfit_1.5-9.1             
 [73] tidyselect_0.2.5            rlang_0.3.1                 AnnotationDbi_1.44.0       
 [76] munsell_0.5.0               tools_3.5.2                 downloader_0.4             
 [79] cli_1.0.1                   generics_0.0.2              RSQLite_2.1.1              
 [82] devtools_2.0.1              broom_0.5.1                 stringr_1.3.1              
 [85] yaml_2.2.0                  processx_3.2.1              knitr_1.21                 
 [88] bit64_0.9-7                 fs_1.2.6                    survMisc_0.5.5             
 [91] purrr_0.2.5                 bindrcpp_0.2.2              EDASeq_2.16.1              
 [94] nlme_3.1-137                R.oo_1.22.0                 xml2_1.2.0                 
 [97] biomaRt_2.38.0              compiler_3.5.2              rstudioapi_0.9.0           
[100] curl_3.2                    testthat_2.0.1              tibble_2.0.0               
[103] geneplotter_1.60.0          stringi_1.2.4               highr_0.7                  
[106] ps_1.3.0                    GenomicFeatures_1.34.1      desc_1.2.0                 
[109] lattice_0.20-38             Matrix_1.2-15               KMsurv_0.1-5               
[112] pillar_1.3.1                BiocManager_1.30.4          GlobalOptions_0.1.0        
[115] data.table_1.11.8           bitops_1.0-6                rtracklayer_1.42.1         
[118] GenomicRanges_1.34.0        R6_2.3.0                    latticeExtra_0.6-28        
[121] hwriter_1.3.2               ShortRead_1.40.0            gridExtra_2.3              
[124] IRanges_2.16.0              sessioninfo_1.1.1           codetools_0.2-16           
[127] assertthat_0.2.0            pkgload_1.0.2               SummarizedExperiment_1.12.0
[130] rprojroot_1.3-2             rjson_0.2.20                withr_2.1.2                
[133] GenomicAlignments_1.18.1    Rsamtools_1.34.0            S4Vectors_0.20.1           
[136] GenomeInfoDbData_1.2.0      mgcv_1.8-26                 parallel_3.5.2             
[139] hms_0.4.2                   grid_3.5.2                  tidyr_0.8.2                
[142] ggpubr_0.2                  Biobase_2.42.0   

Thank you in advance for the attention,
Jéssica.

**Comment by tiagochst** [comment]
Hi, 

the data type "Gene Level Copy Number Scores" is only available in the harmonized database (picture below) and since this data type was included in GDC last month, I just add support this week, but I believe you have the right version.


The code would be:
```
query <- GDCquery(project = "TCGA-ACC",
             data.category = "Copy Number Variation",
             data.type = "Gene Level Copy Number Scores",              
             access="open")
GDCdownload(query)
data <- GDCprepare(query)

```

But if you want GISTIC2 results for hg19, you can have it from https://gdac.broadinstitute.org/


<img width="487" alt="screen shot 2019-01-09 at 12 19 03 pm" src="https://user-images.githubusercontent.com/145529/50919731-3b14f080-1409-11e9-9c3e-7d3c08541691.png">

**Comment by FiveThirteen** [comment]
I agree with JessicaCruz31. This is still happening - I think something changed with GDCprepare. The same script that ran fine a month ago now isn't working and gives the same error JessicaCruz31 gets.

If I run the following code that you suggested:
query <- GDCquery(project = "TCGA-ACC",
             data.category = "Copy Number Variation",
             data.type = "Gene Level Copy Number Scores",              
             access="open")
GDCdownload(query)
data <- GDCprepare(query)

I get the following error:
Reading GISTIC file
Parsed with column specification:
cols(
  .default = col_double(),
  `Gene Symbol` = col_character(),
  Cytoband = col_character()
)
See spec(...) for full column specifications.
Error in stri_split_regex(string, pattern, n = n, simplify = simplify,  : 
  object 'res' not found

**Comment by tiagochst** [comment]
There was a bug, could you update the package. It should be working now.

**Comment by FiveThirteen** [comment]
Thank you Tiago. I updated to the latest TCGAbiolinks package and neither code works (neither the legacy nor the harmonized code above). I am running it on a Mac but I can try to run it on Linux tomorrow in case only the linux package was updated.

> R version 3.5.2 (2018-12-20)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Mojave 10.14.2
> 
> Matrix products: default
> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] bindrcpp_0.2.2              dplyr_0.7.8                 SummarizedExperiment_1.12.0
>  [4] DelayedArray_0.8.0          BiocParallel_1.16.5         matrixStats_0.54.0         
>  [7] Biobase_2.42.0              GenomicRanges_1.34.0        GenomeInfoDb_1.18.1        
> [10] IRanges_2.16.0              S4Vectors_0.20.1            BiocGenerics_0.28.0        
> [13] TCGAbiolinks_2.10.2         beepr_1.3                  
>

**Comment by tiagochst** [comment]
The last version of the package 2.11.2. You can install it from github. The changes I made should be in a couple of day in Bioconductor. 
For the moment, you can install from github with 
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by FiveThirteen** [comment]
Harmonized query now works, thank you Dr. Silva!

**Comment by itikadi** [comment]
Dear Tiago,
I am wondering if the issue reported by JessicaCruz31 has been resolved yet. I am attempting to run your workflow on a linux machine R 3.5.2 and I get the same error:

Error in if (query$data.type == "Gene Level Copy Number Scores") { : 
  missing value where TRUE/FALSE needed

 I have updated the package but nothing doing. Any further help?
Thanks a lot for your attention.

**Comment by tiagochst** [comment]
@itikadi Could you send the query code you are using? Also, could you check if you have the 2.11.2 version of TCGAbiolinks?

**Comment by itikadi** [comment]
@tiagochst Thanks for your prompt response. Much appreciated.
I actually have version 2.11.4 of TCGAbiolinks package and the query is simply what you have in the workflow:
query.gbm.nocnv <- GDCquery(project = "TCGA-GBM",
                            data.category = "Copy number variation",
                            legacy = TRUE,
                            file.type = "nocnv_hg19.seg",
                            sample.type = c("Primary solid Tumor"))
query.gbm.nocnv$results[[1]] <- query.gbm.nocnv$results[[1]][1:20,]
gbm.nocnv <- GDCprepare(query.gbm.nocnv, save = TRUE, save.filename = "GBMnocnvhg19.rda")
I wanted to follow this as is before I start goofing around!

**Comment by tiagochst** [comment]
Yes, there was a bug for hg19 CNV that was introduced when I add the GISTIC2 option.

It should be fixed now since I was able to run the examples below:

```
library(TCGAbiolinks)
# Get CNV for hg19
query.gbm.nocnv <- GDCquery(project = "TCGA-GBM",
                            data.category = "Copy number variation",
                            legacy = TRUE,
                            file.type = "nocnv_hg19.seg",
                            sample.type = c("Primary solid Tumor"))
query.gbm.nocnv$results[[1]] <- query.gbm.nocnv$results[[1]][1:20,]
GDCdownload(query.gbm.nocnv)
gbm.nocnv <- GDCprepare(query.gbm.nocnv, save = TRUE, save.filename = "GBMnocnvhg19.rda")

# Get GISTIC hg38
query.gistic <- GDCquery(project = "TCGA-ACC",
                         data.category = "Copy Number Variation",
                         data.type = "Gene Level Copy Number Scores",              
                         access="open")
GDCdownload(query.gistic)
gistic <- GDCprepare(query.gistic)

# Get CNV hg38
query <- GDCquery(project = "TCGA-ACC", 
                  data.category = "Copy Number Variation",
                  data.type = "Copy Number Segment",
                  barcode = c( "TCGA-OR-A5KU-01A-11D-A29H-01", "TCGA-OR-A5JK-01A-11D-A29H-01"))
GDCdownload(query)
data <- GDCprepare(query)
```

The changes will take some days to be in Bioconductor, please could you reinstall from github with the following R command: `devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by itikadi** [comment]
@tiagochst Works beautifully. Thank you.

**Comment by andreselia** [comment]
Hi! @tiagochst, I have a problem with gdcprepare. I downloaded a query for RNAseq data from the legacy archive, but when I ran gdcprepare, I observed that the data has duplicated genes. It supposed to be 20530 genes, but the function loads 2100, and when I clean the duplicated ones, it only keeps 19800 genes.
PD: the data were downloaded Ok (1098 cases)

This is my query
query.exp <- GDCquery(project = "TCGA-BRCA",
                           data.category = "Gene expression",
                           data.type = "Gene expression quantification",
                           platform = "Illumina HiSeq", 
                           file.type  = "results",
                           experimental.strategy = "RNA-Seq",
                           legacy = TRUE)
GDCdownload(query, method = "api")
data<- GDCprepare(query = query.exp, save = TRUE, save.filename = "data.rda")

**Comment by tiagochst** [comment]
@andreselia Thanks for noticing it. It seems there was a change this year in the data returned by biomart in which some entrezid were mapped to more than one gene name and ENSEMBL ID (example below).
I fixed that for the hg38 data, but I forget to fix for hg19.  I just made the change and if you update the package from GitHub with `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")` it should be fine. 

<img width="687" alt="Screen Shot 2019-07-26 at 11 09 22 AM" src="https://user-images.githubusercontent.com/145529/61972630-ea28ac00-af96-11e9-873b-19aa57ddc02e.png">

**Comment by andreselia** [comment]
Hi @tiagochst, thanks for your reply. I downloaded the updated package and do gdcpreare to the query. The final count of genes was around 1900, is that ok? I was expecting 20531. And it is still having some duplicated genes (when I cleaned it, it kept around 1600 genes).
In order to check that the files were the problem, I joined all the files ".results" in one dataframe with dplyr package, there wasn't duplicated genes and the 20531 genes where on the list. Here is the script:
library(dplyr)
Allfiles = list.files(pattern = ".results", recursive = TRUE)
for (archivo in Allfiles){
  #create the new file in the first iteration of the loop by checking if it exists
  if(!exists("dat")){dat = read.delim(archivo, stringsAsFactors = FALSE)[,1:2]} 
  if(exists("dat")){
    temp = read.delim(archivo,  stringsAsFactors = FALSE)[,1:2]
    dat = full_join(dat, temp, by = "gene_id")
  }
}

**Comment by tiagochst** [comment]
I'll recheck, I got 20531 genes when I ran last time.

**Comment by tiagochst** [comment]
Sorry, I am wrong. 

The main problem is that we are using entrez id to map to genomic coordinates. 
And some  of the entrez id  were updated (such as https://www.ncbi.nlm.nih.gov/gene/221016). If you map to coordinates by either gene name (we have gene names as ?) or entrez id you will lose some genes. 

If you want the unmodified version just set   `summarizedExperiment` to `FALSE`
`data GDCprepare(query,summarizedExperiment = FALSE)`, but there will be no genomic coordinates added.

**Comment by andreselia** [comment]
Thanks! I do not need the genomic coordinates by now.
