### ISSUE TITLE
GDCquery error: Error in value[[3L]](cond)

### ISSUE THREAD

**Issue by xiaojuhu** [BioinformaticsFMRP/TCGAbiolinks#71]
Hi TCGAbiolinks:
when I use query_LUAD<-GDCquery(project = "TCGA-LUAD") to download data, there was error like: 
Error in value[[3L]](cond) : 
  GDC server down, try to use this package later

Then how to solve this problem.

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.2 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] TCGAbiolinks_2.2.9

loaded via a namespace (and not attached):
  [1] circlize_0.3.9              fastmatch_1.1-0            
  [3] aroma.light_3.4.0           plyr_1.8.4                 
  [5] igraph_1.0.1                selectr_0.3-1              
  [7] ConsensusClusterPlus_1.38.0 lazyeval_0.2.0             
  [9] splines_3.3.1               BiocParallel_1.8.1         
 [11] pathview_1.14.0             GenomeInfoDb_1.10.3        
 [13] ggplot2_2.2.1               digest_0.6.12              
 [15] foreach_1.4.3               BiocInstaller_1.24.0       
 [17] GOSemSim_2.0.4              viridis_0.3.4              
 [19] GO.db_3.4.0                 gdata_2.17.0               
 [21] magrittr_1.5                memoise_1.0.0              
 [23] cluster_2.0.5               doParallel_1.0.10          
 [25] limma_3.30.12               ComplexHeatmap_1.12.0      
 [27] Biostrings_2.42.1           readr_1.0.0                
 [29] annotate_1.52.1             matrixStats_0.51.0         
 [31] R.utils_2.5.0               colorspace_1.3-2           
 [33] rvest_0.3.2                 ggrepel_0.6.5              
 [35] dplyr_0.5.0                 RCurl_1.95-4.8             
 [37] jsonlite_1.3                hexbin_1.27.1              
 [39] graph_1.52.0                genefilter_1.56.0          
 [41] supraHex_1.12.0             survival_2.40-1            
 [43] iterators_1.0.8             ape_4.1                    
 [45] survminer_0.2.4             gtable_0.2.0               
 [47] zlibbioc_1.20.0             XVector_0.14.0             
 [49] GetoptLong_0.1.5            kernlab_0.9-25             
 [51] Rgraphviz_2.18.0            shape_1.4.2                
 [53] prabclus_2.2-6              BiocGenerics_0.20.0        
 [55] DEoptimR_1.0-8              scales_0.4.1               
 [57] DOSE_3.0.10                 DESeq_1.26.0               
 [59] mvtnorm_1.0-6               DBI_0.5-1                  
 [61] edgeR_3.16.5                ggthemes_3.4.0             
 [63] Rcpp_0.12.9                 xtable_1.8-2               
 [65] matlab_1.0.2                mclust_5.2.2               
 [67] preprocessCore_1.36.0       stats4_3.3.1               
 [69] httr_1.2.1                  fgsea_1.0.2                
 [71] gplots_3.0.1                RColorBrewer_1.1-2         
 [73] fpc_2.1-10                  modeltools_0.2-21          
 [75] XML_3.98-1.5                R.methodsS3_1.7.1          
 [77] flexmix_2.3-13              nnet_7.3-12                
 [79] locfit_1.5-9.1              reshape2_1.4.2             
 [81] AnnotationDbi_1.36.2        munsell_0.4.3              
 [83] tools_3.3.1                 downloader_0.4             
 [85] RSQLite_1.1-2               stringr_1.2.0              
 [87] knitr_1.15.1                robustbase_0.92-7          
 [89] caTools_1.17.1              KEGGREST_1.14.0            
 [91] dendextend_1.4.0            EDASeq_2.8.0               
 [93] nlme_3.1-131                c3net_1.1.1                
 [95] whisker_0.3-2               R.oo_1.21.0                
 [97] KEGGgraph_1.32.0            DO.db_2.9                  
 [99] xml2_1.1.1                  biomaRt_2.30.0             
[101] curl_2.3                    png_0.1-7                  
[103] affyio_1.44.0               minet_3.32.0               
[105] tibble_1.2                  geneplotter_1.52.0         
[107] stringi_1.1.2               GenomicFeatures_1.26.3     
[109] lattice_0.20-34             trimcluster_0.1-2          
[111] Matrix_1.2-8                GlobalOptions_0.0.10       
[113] data.table_1.10.4           bitops_1.0-6               
[115] parmigene_1.0.2             dnet_1.0.10                
[117] rtracklayer_1.34.2          GenomicRanges_1.26.3       
[119] qvalue_2.6.0                R6_2.2.0                   
[121] latticeExtra_0.6-28         affy_1.52.0                
[123] hwriter_1.3.2               ShortRead_1.32.0           
[125] KernSmooth_2.23-15          gridExtra_2.2.1            
[127] IRanges_2.8.1               codetools_0.2-15           
[129] MASS_7.3-45                 gtools_3.5.0               
[131] assertthat_0.1              SummarizedExperiment_1.4.0 
[133] rjson_0.2.15                GenomicAlignments_1.10.0   
[135] Rsamtools_1.26.1            S4Vectors_0.12.1           
[137] diptest_0.75-7              parallel_3.3.1             
[139] clusterProfiler_3.2.11      grid_3.3.1                 
[141] tidyr_0.6.1                 class_7.3-14               
[143] Biobase_2.34.0

**Comment by tiagochst** [comment]
This problem still continues? 
This should be a not permanent problem. If GDC is unreachable for any reason (maintenance), this message should appear:
> GDC server down, try to use this package later
But if GDC is working it should not appear.

**Comment by petrtau** [comment]
Hi,
I got same error now.

**Comment by tiagochst** [comment]
We are developing a new version that uses other libraries to access the API.
Please, could you install this version and see if the problem still continues?

```
source('https://bioconductor.org/biocLite.R')
biocLite('Bioconductor/GenomicDataCommons')
biocLite('BioinformaticsFMRP/TCGAbiolinks',ref = "GenomicDataCommons")
```

**Comment by tiagochst** [comment]
Also, can you send me the sessionInfo()

For the   CentOS. One of the users had a similar problem with CentOS Linux release 7.1.1503,R  3.3.1  Bioconductor 3.3 and libcurl-7.29.0-25. He updated CentOS and it worked.

**Comment by petrtau** [comment]
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by tiagochst** [comment]
Please, can you also send me the code of the query and the TCGAbiolinks package version?

**Comment by petrtau** [comment]
I used the code that is in case study n.1 to test it https://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/tcgaBiolinks.html#tcga_downstream_analysis:_case_studies . 
I wasn't able to install new version since it requires R.3.4. However I don't need it now since I found out that on TCGA are not suitable data for my purpose.
Anyway thank you so much.

**Comment by lasandrall** [comment]
Hi tiagochst,
I get the same error when I try to run GDCquery. I downloaded the source files, manually sourced it and tried to run the query below but get errors. 
query.met <- GDCquery(project = c("TCGA-BRCA"),
                      data.category = "DNA Methylation",
                      platform = c("Illumina Human Methylation 450"))
How do I go about it? 
Thanks.

**Comment by tiagochst** [comment]
@lasandrall can you send me your `sessionInfo()` ?

**Comment by lasandrall** [comment]
R version 3.4.0 (2017-04-21) Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1 Matrix products:
default locale: [1] LC_COLLATE=English_United States.1252
LC_CTYPE=English_United States.1252 LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C LC_TIME=English_United States.1252 attached base packages:
[1] stats graphics grDevices utils datasets methods base loaded via a
namespace (and not attached): [1] compiler_3.4.0 tools_3.4.0


Thank you.

**Comment by tiagochst** [comment]
I don't have a windows to test. Does the following code gives you an error?

```
library(TCGAbiolinks)
library(httr)
library(jsonlite)
url <- TCGAbiolinks:::getGDCquery(project = "TCGA-BRCA",
                   data.category = "DNA Methylation",
                   data.type = NA,
                   legacy = FALSE,workflow.type = NA,
                    platform = c("Illumina Human Methylation 450"))

aux <- GET(url)
aux <- content(aux, as = "text", encoding = "UTF-8")
results <- fromJSON(aux, simplifyDataFrame = TRUE)

```

**Comment by lasandrall** [comment]
Thank you.
I get the following error when I run this code:

> library(TCGAbiolinks)Error: package or namespace load failed for ‘TCGAbiolinks’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘GlobalOptions’> library(httr)>
library(jsonlite)> url <- TCGAbiolinks:::getGDCquery(project =
"TCGA-BRCA",+                                   data.category = "DNA
Methylation",+                                   data.type = NA,+
                             legacy = FALSE,workflow.type = NA,+
                            platform = c("Illumina Human Methylation
450"))Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()),
versionCheck = vI[[j]]) :
  there is no package called ‘GlobalOptions’

**Comment by tiagochst** [comment]
can you install this package GlobalOptions and try again: `install.packages("GlobalOptions")`

**Comment by lasandrall** [comment]
Hi,
Thanks. I think there is an error internally. I install that but when I run
I get the error below:

library(TCGAbiolinks)Error: package or namespace load failed for
‘TCGAbiolinks’ in loadNamespace(i, c(lib.loc, .libPaths()),
versionCheck = vI[[i]]):
 there is no package called ‘mclust’


I then install 'mclust', and I get another error for the package'

there is no package called ‘RSQLite’



It keeps bringing up different packages. I was under the impression that
TCGAbiolinks will import and install the packages it requires?

Thanks,
Sandra.

**Comment by lasandrall** [comment]
Thanks.

I get the same issue- it keep saying error in several packages.

* installing *source* package 'TCGAbiolinks' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()),
versionCheck = vI[[j]]) :
  there is no package called 'mnormt'
ERROR: lazy loading failed for package 'TCGAbiolinks'




I also tried

> source("https://bioconductor.org/biocLite.R")Bioconductor version 3.5 (BiocInstaller 1.26.0), ?biocLite for help> biocLite("TCGAbiolinks")BioC_mirror: https://bioconductor.orgUsing Bioconductor 3.5 (BiocInstaller 1.26.0), R 3.4.0 (2017-04-21).Installing package(s) ‘TCGAbiolinks’trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/TCGAbiolinks_2.4.3.zip'Content type 'application/zip' length 86283520 bytes (82.3 MB)downloaded 82.3 MB
package ‘TCGAbiolinks’ successfully unpacked and MD5 sums checked

> query.met <- GDCquery(project = c("TCGA-BRCA"),+                       data.category = "DNA Methylation",+                       platform = c("Illumina Human Methylation 450"))--------------------------------------o GDCquery: Searching in GDC database--------------------------------------
[image: Inline image 4] Show Traceback
 [image: Inline image 3] Rerun with Debug
 Error in str_split(x, "-") : could not find function "str_split"


Thanks.

I appreciate your help.

Sandra.

**Comment by modarzi** [comment]
Hi,
I need to download TCGA-SARC Trancriptomics profiling  from TCGA. and using 2 packages:
library(TCGAbiolinks);
library(SummarizedExperiment);
then I define my query based on GDCquery function. then by below commands try to download:
GDCdownload(query)
data <- GDCprepare(query)
 
but I receive below messages:

|=========================================================| 100%    1 MB
  |========================================================| 100%
Starting to add information to samples
 => Add clinical information to samples
Add FFPE information. More information at: 
=> https://cancergenome.nih.gov/cancersselected/biospeccriteria 
=> http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html
 => Adding subtype information to samples
sarc subtype information from:doi:10.1016/j.cell.2017.10.014
Error in gene.location$ensembl_gene_id : 
  $ operator is invalid for atomic vectors 

My RStudio is based on win 10 and My R version is 3.3. also I updated my TCGAbiolinks based on below command:
devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks",dependencies = T)

Now, what should I do for solving this Error and get Transcriptions Profiling from TCGA?
Best Regards,
Mohammad

**Comment by tiagochst** [comment]
Hello,

in that part of the code we execute biomaRt to access EMSEMBL database.
Please, could you update biomaRt `devtools::install_github(repo = "grimbough/biomaRt",dependencies = T)`
 and send me your `sessionInfo()` in case it still not working.

Best regards,
Tiago

**Comment by modarzi** [comment]
before updating biomaRT, I have to say that I execute my code again and receive below message:
> data <- GDCprepare(query)
|=========================================================| 100%    1 MB
|=========================================================| 100%    1 MB
|=========================================================| 100%    1 MB
|=========================================================| 100%    1 MB
|======================================================| 100%    1 MB
  |======================================================| 100%
Starting to add information to samples
 => Add clinical information to samples
Add FFPE information. More information at: 
=> https://cancergenome.nih.gov/cancersselected/biospeccriteria 
=> http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html
 => Adding subtype information to samples
sarc subtype information from:doi:10.1016/j.cell.2017.10.014
Downloading genome information (try:0) Using: Human genes (GRCh38.p10)
Loading from disk
From the 60483 genes we couldn't map 3520

so by this message again your comment is updating biomaRt?
Best Regards,
Mohammad

**Comment by tiagochst** [comment]
The message seems right. I believe the prepare was executed. Is the data object empty?

**Comment by modarzi** [comment]
sorry for this question but in which directory  can I  find  downloaded data?

**Comment by tiagochst** [comment]
Your output is an R object (SummarizedExperiment). There is a picture of the object in the manual below
https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html

You will be able to access the data using the `assay` function and metadata with `rowRanges` and `ColData`

There are some examples in the manual https://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/download_prepare.html

If you want a csv file. You can do something like: `write.csv(assay(data),"export.csv)`

**Comment by modarzi** [comment]
Hi,
Thanks for your comments. I have another questions. I need Normalized value of Gene Expression data from TCGA. So, I define my query based on below syntax:
query <- GDCquery(project = "TCGA-SARC",sample.type = "Primary solid Tumor",
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification",workflow.type = "HTSeq - FPKM-UQ")
So, My question is that is this query true for getting Normalized GE data?
and my second question is can I define especial query for downloading GE data binding with Clinical data at the same time?
and third question is how can I save R object (SummarizedExperiment). because in write.csv(assay(data),"export.csv) command saves just one dimension of this object. in the other words, now I shutdown my system and how can I load R object (SummarizedExperiment) again when I start my RStudio?
Best Regards,
Mohammad

**Comment by tiagochst** [comment]
1) Yes, the description can be found here https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline/#mrna-expression-normalization. For some packages you might need to work with raw counts instead of FPKM-UQ (Like DESeq2, a workflow is described at Bioconductor website https://www.bioconductor.org/help/workflows/rnaseqGene/)
2) The Clinical data is available in the `ColData` dimension, there is no other way TCGAbiolinks represents clinical data together with molecular that but the Summarized Experiment object
3) You can use the command `save` from R (i.e save`(data,file = "FPKM-UQ.rda")`, or there is one

**Comment by modarzi** [comment]
Hi,

I hope that you are all well.  today, I tried to download TCGA data for another Cancer and based on your advise, I run below command:

devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks",dependencies = T)
 but I receive some warnings and Errors as in below:

installing *source* package 'TCGAbiolinks' ...
** R
** data
*** moving datasets to lazyload DB
Warning: namespace 'GenomicRanges' is not available and has been replaced
by .GlobalEnv when processing object 'dataREAD'
Warning: namespace 'GenomicRanges' is not available and has been replaced
by .GlobalEnv when processing object 'dataREAD'
Warning: namespace 'SummarizedExperiment' is not available and has been replaced
by .GlobalEnv when processing object 'gbm.exp.harmonized'
Warning: namespace 'SummarizedExperiment' is not available and has been replaced
by .GlobalEnv when processing object 'gbm.exp.harmonized'
Warning: namespace 'SummarizedExperiment' is not available and has been replaced
by .GlobalEnv when processing object 'gbm.exp.legacy'
Warning: namespace 'SummarizedExperiment' is not available and has been replaced
by .GlobalEnv when processing object 'gbm.exp.legacy'
Warning: namespace 'SummarizedExperiment' is not available and has been replaced
by .GlobalEnv when processing object 'met.gbm.27k'
Warning: namespace 'SummarizedExperiment' is not available and has been replaced
by .GlobalEnv when processing object 'met.gbm.27k'
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'GenomeInfoDbData'
ERROR: lazy loading failed for package 'TCGAbiolinks'
* removing 'C:/Users/C1/Documents/R/win-library/3.4/TCGAbiolinks'
In R CMD INSTALL
Installation failed: Command failed (1)


I appreciate if you share your comment with me.
Best Regards,
Mohammad

**Comment by tiagochst** [comment]
A dependency package  GenomeInfoDbData was not installed.
If you run this commands, it should be installed:

source("https://bioconductor.org/biocLite.R")
biocLite("GenomeInfoDbData");
devtools::install_github(repo =
"BioinformaticsFMRP/TCGAbiolinks",dependencies = T)

Best regards,
Tiago Chedraoui Silva

**Comment by modarzi** [comment]
Thanks for your comment. Now I am downloading DNA Methylation of one cancer that it has 19 GB. so, it is progressing chunk by chunk and up to know, it has been downloaded above 3 chunk(1.5 GB).my question is can I interrupt it and then start at other time by resuming last downloaded files? or If I cancel it, I have to start download again?
Best Regards,

**Comment by tiagochst** [comment]
You can I interrupt it and then start at other time, it will download only the missing ones.
For DNA methylation it is better to have more chunks.

**Comment by tiagochst** [comment]
The GenomicDataCommons is an old branch we were trying to integrate with
another package (GenomicDataCommons). Unfortunately, I did not had time to
finish it.
To get the last version of TCGAbiolinks, please, use the master branch.

source('https://bioconductor.org/biocLite.R')
biocLite('BioinformaticsFMRP/TCGAbiolinks")




Tiago Chedraoui Silva

**Comment by bhowmickrupa** [comment]
I am trying to obtain the latest version of GDC through:
source('https://bioconductor.org/biocLite.R')
biocLite('BioinformaticsFMRP/TCGAbiolinks')

But I am getting this error everytime:
Error in utils::download.file(url, path, method = download_method(), quiet
= quiet,  :
  cannot open URL '
https://api.github.com/repos/BioinformaticsFMRP/TCGAbiolinks/zipball/master'

I checked the availability of download.file in R.utils which is available.
Still I am getting this error. I dont know how to sort it. Can you help me
out.

With Regards,

Rupa Bhowmick
Project Fellow
C/O- Dr. Ram Rup Sarkar
Chemical Engineering and Process Development
CSIR-National Chemical Laboratory
Dr. Homi Bhabha Road,
Pashan, Pune-411008

**Comment by tiagochst** [comment]
@bhowmickrupa I'm not 100% which is the problem, but the "Error in value[[3L]](cond)" normally happens due to network problems. The comunnication between GDC through the API was not successful.

This command should be working, it is weird it was not able to access github.
```
source('https://bioconductor.org/biocLite.R')
biocLite('BioinformaticsFMRP/TCGAbiolinks')
```

Can you try:
```
devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")
```

Also, do you have an updated version of R; curl and httr  packages ?
If yes, I would say something is affecting the connection (firewall, etc)

**Comment by bhowmickrupa** [comment]
I downloaded the zip file for "TCGAbiolinks-master" from the
github.io/BioinformaticsFMRP source and installed in the same R folder as
the one in which TCGAbiolinks was installed. The installation went all
right, but now when I try to download a query through the same, I am
getting the 3L error again. You are probably right with the network
problem. I have proxies made in my institute network. Can that be a
problem? Can you suggest me any way I can try to solve this?

With Regards,

Rupa Bhowmick
Project Fellow
C/O- Dr. Ram Rup Sarkar
Chemical Engineering and Process Development
CSIR-National Chemical Laboratory
Dr. Homi Bhabha Road,
Pashan, Pune-411008

**Comment by modarzi** [comment]
Hi,
I upgraded my R version to 3.5.0 (2018-04-23).Now I want to run below query but I receive Error:

> query <- GDCquery(project = "TCGA-BRCA", data.category = "Protein expression", legacy = TRUE)
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-BRCA
Error:  Error in getURL(url, fromJSON, timeout(600), simplifyDataFrame = TRUE): 'getURL()' failed:
  URL: https://gdc-api.nci.nih.gov/legacy/files/?pretty=true&fields=archive.revision,archive.file_name,md5sum,state,data_category,file_id,platform,file_name,file_size,md5sum,submitter_id,data_type&expand=cases.samples.portions,cases.project,center,analysis&size=1134&filters=%7B%22op%22:%22and%22,%22content%22:[%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.project_id%22,%22value%22:[%22TCGA-BRCA%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_category%22,%22value%22:[%22Protein%20expression%22]%7D%7D]%7D&format=JSON
  error: Failure when receiving data from the peer

We will retry to access GDC!
Error in if (json$data$pagination$count == 0) { : 
  argument is of length zero

I appereciate if you share your comment with me.

Best Regards,
Mohammad

**Comment by tstokowy** [comment]
Hi, I get the same error on Mac and Ubuntu Linux, tried to connect from Norway, both work and home:

CancerProject <- "TCGA-BRCA"
DataDirectory <- paste0("../GDC/",gsub("-","_",CancerProject))
FileNameData <- paste0(DataDirectory, "_","miRNA_gene_quantification",".rda")

query.miR <- GDCquery(project = CancerProject, 
                      data.category = "Gene expression",
                      data.type = "miRNA gene quantification",
                      file.type = "hg19.mirna",
                      legacy = TRUE)

Error in value[[3L]](cond) : 
  GDC server down, try to use this package later

The server status seems to be OK, but GDCquery fails.
> GenomicDataCommons::status()
$commit
[1] "e9e20d6f97f2bf6dd3b3261e36ead57c56a4c7cc"
$data_release
[1] "Data Release 12.0 - June 13, 2018"
$status
[1] "OK"
$tag
[1] "1.14.1"
$version
[1] 1

I will be thankful for your suggestions,

--
Tomasz Stokowy


> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] swirl_2.4.3          BiocInstaller_1.28.0 httr_1.3.1           RCurl_1.95-4.10     
[5] bitops_1.0-6         TCGAbiolinks_2.6.12 

loaded via a namespace (and not attached):
  [1] circlize_0.4.4              aroma.light_3.8.0           plyr_1.8.4                 
  [4] selectr_0.4-1               ConsensusClusterPlus_1.42.0 lazyeval_0.2.1             
  [7] splines_3.4.4               BiocParallel_1.12.0         GenomeInfoDb_1.14.0        
 [10] ggplot2_2.2.1               sva_3.26.0                  digest_0.6.15              
 [13] foreach_1.4.4               magrittr_1.5                memoise_1.1.0              
 [16] cluster_2.0.7-1             doParallel_1.0.11           limma_3.34.9               
 [19] ComplexHeatmap_1.17.1       Biostrings_2.46.0           readr_1.1.1                
 [22] annotate_1.56.2             matrixStats_0.53.1          R.utils_2.6.0              
 [25] prettyunits_1.0.2           colorspace_1.3-2            blob_1.1.1                 
 [28] rvest_0.3.2                 ggrepel_0.8.0               dplyr_0.7.6                
 [31] crayon_1.3.4                jsonlite_1.5                genefilter_1.60.0          
 [34] bindr_0.1.1                 survival_2.42-4             zoo_1.8-2                  
 [37] iterators_1.0.9             glue_1.2.0                  survminer_0.4.2            
 [40] GenomicDataCommons_1.5.3    gtable_0.2.0                zlibbioc_1.24.0            
 [43] XVector_0.18.0              GetoptLong_0.1.7            DelayedArray_0.4.1         
 [46] shape_1.4.4                 BiocGenerics_0.24.0         scales_0.5.0               
 [49] DESeq_1.30.0                DBI_1.0.0                   edgeR_3.20.9               
 [52] ggthemes_3.5.0              Rcpp_0.12.17                xtable_1.8-2               
 [55] progress_1.2.0              cmprsk_2.2-7                foreign_0.8-70             
 [58] bit_1.1-14                  matlab_1.0.2                km.ci_0.5-2                
 [61] stats4_3.4.4                RColorBrewer_1.1-2          pkgconfig_2.0.1            
 [64] XML_3.98-1.11               R.methodsS3_1.7.1           locfit_1.5-9.1             
 [67] tidyselect_0.2.4            rlang_0.2.1                 reshape2_1.4.3             
 [70] AnnotationDbi_1.40.0        munsell_0.5.0               tools_3.4.4                
 [73] downloader_0.4              RSQLite_2.1.1               devtools_1.13.6            
 [76] broom_0.4.4                 stringr_1.3.1               yaml_2.1.19                
 [79] knitr_1.20                  bit64_0.9-7                 survMisc_0.5.4             
 [82] purrr_0.2.5                 bindrcpp_0.2.2              EDASeq_2.12.0              
 [85] nlme_3.1-137                R.oo_1.22.0                 xml2_1.2.0                 
 [88] biomaRt_2.34.2              compiler_3.4.4              rstudioapi_0.7             
 [91] curl_3.2                    testthat_2.0.0              tibble_1.4.2               
 [94] geneplotter_1.56.0          stringi_1.2.3               GenomicFeatures_1.30.3     
 [97] lattice_0.20-35             Matrix_1.2-14               psych_1.8.4                
[100] KMsurv_0.1-5                pillar_1.2.3                GlobalOptions_0.1.0        
[103] data.table_1.11.4           rtracklayer_1.38.3          GenomicRanges_1.30.3       
[106] R6_2.2.2                    latticeExtra_0.6-28         hwriter_1.3.2              
[109] RMySQL_0.10.15              ShortRead_1.36.1            gridExtra_2.3              
[112] IRanges_2.12.0              codetools_0.2-15            assertthat_0.2.0           
[115] SummarizedExperiment_1.8.1  rjson_0.2.20                withr_2.1.2                
[118] GenomicAlignments_1.14.2    Rsamtools_1.30.0            mnormt_1.5-5               
[121] S4Vectors_0.16.0            GenomeInfoDbData_1.0.0      mgcv_1.8-23                
[124] parallel_3.4.4              hms_0.4.2                   grid_3.4.4                 
[127] tidyr_0.8.1                 git2r_0.21.0                ggpubr_0.1.7               
[130] Biobase_2.38.0

**Comment by tiagochst** [comment]
@tstokowy  The query should be the one below:

```
query.miR <- GDCquery(project = CancerProject,
                      data.category = "Gene expression",
                      data.type = "miRNA gene quantification",
                      file.type = "hg19.mirbase20",
                      legacy = TRUE)

```
Otherwise this will be outputed.
<img width="742" alt="screen shot 2018-07-01 at 3 58 57 pm" src="https://user-images.githubusercontent.com/145529/42137708-d5359538-7d47-11e8-88be-257b3aa79002.png">

You have TCGAbiolinks_2.6.12 is it possible to update it? The GDC API has changed. And only versions hihger 2.8 should be working.

**Comment by tstokowy** [comment]
Thanks, this worked perfectly! This package is very useful, I will definitely use it in my work.

All the best,

--
Tomasz

**Comment by swhite202** [comment]
Hello,

I have updated the TCGAbiolinks package to 2.9.2 but am still getting this issue.

> query <- GDCquery(project = "TCGA-KIRC", 
+                   data.category = "Transcriptome Profiling", 
+                   data.type = "Gene Expression Quantification", 
+                   workflow.type = "HTSeq - FPKM-UQ")
Error in value[[3L]](cond) : 
  GDC server down, try to use this package later

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] TCGAbiolinks_2.9.2

loaded via a namespace (and not attached):
  [1] colorspace_1.3-2            selectr_0.4-1               rjson_0.2.20                hwriter_1.3.2              
  [5] circlize_0.4.4              XVector_0.20.0              GenomicRanges_1.32.4        GlobalOptions_0.1.0        
  [9] rstudioapi_0.7              ggpubr_0.1.7                matlab_1.0.2                ggrepel_0.8.0              
 [13] bit64_0.9-7                 AnnotationDbi_1.42.1        xml2_1.2.0                  codetools_0.2-15           
 [17] splines_3.5.1               R.methodsS3_1.7.1           mnormt_1.5-5                doParallel_1.0.11          
 [21] DESeq_1.32.0                geneplotter_1.58.0          knitr_1.20                  jsonlite_1.5               
 [25] Rsamtools_1.32.2            km.ci_0.5-2                 broom_0.4.5                 annotate_1.58.0            
 [29] cluster_2.0.7-1             R.oo_1.22.0                 readr_1.1.1                 compiler_3.5.1             
 [33] httr_1.3.1                  assertthat_0.2.0            Matrix_1.2-14               lazyeval_0.2.1             
 [37] limma_3.36.2                prettyunits_1.0.2           tools_3.5.1                 bindrcpp_0.2.2             
 [41] gtable_0.2.0                glue_1.2.0                  GenomeInfoDbData_1.1.0      reshape2_1.4.3             
 [45] dplyr_0.7.6                 ggthemes_3.5.0              ShortRead_1.38.0            Rcpp_0.12.17               
 [49] Biobase_2.40.0              Biostrings_2.48.0           nlme_3.1-137                rtracklayer_1.40.3         
 [53] iterators_1.0.10            psych_1.8.4                 stringr_1.3.1               rvest_0.3.2                
 [57] devtools_1.13.6             XML_3.98-1.11               edgeR_3.22.3                zoo_1.8-2                  
 [61] zlibbioc_1.26.0             scales_0.5.0                aroma.light_3.10.0          BiocInstaller_1.30.0       
 [65] hms_0.4.2                   parallel_3.5.1              SummarizedExperiment_1.10.1 RColorBrewer_1.1-2         
 [69] ComplexHeatmap_1.18.1       yaml_2.1.19                 curl_3.2                    memoise_1.1.0              
 [73] gridExtra_2.3               KMsurv_0.1-5                ggplot2_3.0.0               downloader_0.4             
 [77] biomaRt_2.36.1              latticeExtra_0.6-28         stringi_1.1.7               RSQLite_2.1.1              
 [81] genefilter_1.62.0           S4Vectors_0.18.3            foreach_1.4.4               GenomicFeatures_1.32.0     
 [85] BiocGenerics_0.26.0         BiocParallel_1.14.2         shape_1.4.4                 GenomeInfoDb_1.16.0        
 [89] rlang_0.2.1                 pkgconfig_2.0.1             matrixStats_0.53.1          bitops_1.0-6               
 [93] lattice_0.20-35             purrr_0.2.5                 bindr_0.1.1                 cmprsk_2.2-7               
 [97] GenomicAlignments_1.16.0    bit_1.1-14                  tidyselect_0.2.4            plyr_1.8.4                 
[101] magrittr_1.5                R6_2.2.2                    IRanges_2.14.10             DelayedArray_0.6.1         
[105] DBI_1.0.0                   mgcv_1.8-24                 foreign_0.8-70              pillar_1.3.0               
[109] withr_2.1.2                 survival_2.42-3             RCurl_1.95-4.10             tibble_1.4.2               
[113] EDASeq_2.14.1               crayon_1.3.4                survMisc_0.5.5              GetoptLong_0.1.7           
[117] progress_1.2.0              locfit_1.5-9.1              grid_3.5.1                  sva_3.28.0                 
[121] data.table_1.11.4           blob_1.1.1                  git2r_0.22.1                ConsensusClusterPlus_1.44.0
[125] digest_0.6.15               xtable_1.8-2                tidyr_0.8.1                 R.utils_2.6.0              
[129] stats4_3.5.1                munsell_0.5.0               survminer_0.4.2

**Comment by alanzos** [comment]
Hello, I have the same problem:

```
> library(TCGAbiolinks)
> query <- GDCquery(project = "TCGA-LUAD", data.category = "Clinical",file.type = "xml")
Error in value[[3L]](cond) : 
  GDC server down, try to use this package later
```

I have tried this option:
```
source('https://bioconductor.org/biocLite.R')
biocLite('Bioconductor/GenomicDataCommons')
biocLite('BioinformaticsFMRP/TCGAbiolinks',ref = "GenomicDataCommons")
```

And also this one:
```
devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks", dependencies = T, force=T)
```


And I still get the same error. This is my session info:
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=es_ES.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=es_ES.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] TCGAbiolinks_2.11.0

loaded via a namespace (and not attached):
  [1] colorspace_1.3-2            selectr_0.4-1              
  [3] rjson_0.2.20                hwriter_1.3.2              
  [5] circlize_0.4.5              XVector_0.22.0             
  [7] GenomicRanges_1.34.0        GlobalOptions_0.1.0        
  [9] ggpubr_0.2                  matlab_1.0.2               
 [11] ggrepel_0.8.0               bit64_0.9-7                
 [13] AnnotationDbi_1.44.0        xml2_1.2.0                 
 [15] codetools_0.2-15            splines_3.5.1              
 [17] R.methodsS3_1.7.1           doParallel_1.0.14          
 [19] DESeq_1.34.0                geneplotter_1.60.0         
 [21] knitr_1.20                  jsonlite_1.5               
 [23] Rsamtools_1.34.0            km.ci_0.5-2                
 [25] broom_0.5.0                 annotate_1.60.0            
 [27] cluster_2.0.7-1             R.oo_1.22.0                
 [29] readr_1.2.1                 compiler_3.5.1             
 [31] httr_1.3.1                  backports_1.1.2            
 [33] assertthat_0.2.0            Matrix_1.2-15              
 [35] lazyeval_0.2.1              limma_3.38.2               
 [37] prettyunits_1.0.2           tools_3.5.1                
 [39] bindrcpp_0.2.2              gtable_0.2.0               
 [41] glue_1.3.0                  GenomeInfoDbData_1.2.0     
 [43] dplyr_0.7.8                 ggthemes_4.0.1             
 [45] ShortRead_1.40.0            Rcpp_1.0.0                 
 [47] Biobase_2.42.0              Biostrings_2.50.1          
 [49] nlme_3.1-137                rtracklayer_1.42.0         
 [51] iterators_1.0.10            stringr_1.3.1              
 [53] rvest_0.3.2                 XML_3.98-1.16              
 [55] edgeR_3.24.0                zoo_1.8-4                  
 [57] zlibbioc_1.28.0             scales_1.0.0               
 [59] aroma.light_3.12.0          hms_0.4.2                  
 [61] parallel_3.5.1              SummarizedExperiment_1.12.0
 [63] RColorBrewer_1.1-2          curl_3.2                   
 [65] ComplexHeatmap_1.20.0       memoise_1.1.0              
 [67] gridExtra_2.3               KMsurv_0.1-5               
 [69] ggplot2_3.1.0               downloader_0.4             
 [71] biomaRt_2.38.0              latticeExtra_0.6-28        
 [73] stringi_1.2.4               RSQLite_2.1.1              
 [75] genefilter_1.64.0           S4Vectors_0.20.1           
 [77] foreach_1.4.4               GenomicFeatures_1.34.1     
 [79] BiocGenerics_0.28.0         BiocParallel_1.16.0        
 [81] shape_1.4.4                 GenomeInfoDb_1.18.1        
 [83] rlang_0.3.0.1               pkgconfig_2.0.2            
 [85] matrixStats_0.54.0          bitops_1.0-6               
 [87] lattice_0.20-38             purrr_0.2.5                
 [89] bindr_0.1.1                 GenomicAlignments_1.18.0   
 [91] cmprsk_2.2-7                bit_1.1-14                 
 [93] tidyselect_0.2.5            plyr_1.8.4                 
 [95] magrittr_1.5                R6_2.3.0                   
 [97] IRanges_2.16.0              DelayedArray_0.8.0         
 [99] DBI_1.0.0                   mgcv_1.8-26                
[101] pillar_1.3.0                survival_2.43-1            
[103] RCurl_1.95-4.11             tibble_1.4.2               
[105] EDASeq_2.16.0               crayon_1.3.4               
[107] survMisc_0.5.5              GetoptLong_0.1.7           
[109] progress_1.2.0              locfit_1.5-9.1             
[111] grid_3.5.1                  sva_3.30.0                 
[113] data.table_1.11.8           blob_1.1.1                 
[115] ConsensusClusterPlus_1.46.0 digest_0.6.18              
[117] xtable_1.8-3                tidyr_0.8.2                
[119] R.utils_2.7.0               stats4_3.5.1               
[121] munsell_0.5.0               survminer_0.4.3
```

In the same computer I have dual boot with Windows, and the same commands work perfectly.
Are there other alternatives?

**Comment by mkumravat** [comment]
Hello, I have the same problem

query <- GDCquery(project = "TCGA-LUAD", data.category = "Copy number variation")

Error in value[[3L]](cond) :
  GDC server down, try to use this package later

Also, I've updated my TCGAbiolinks package using : 
devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")

Here is my sessionInfo() : 
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
[1] GlobalOptions_0.1.0 TCGAbiolinks_2.6.12 maftools_1.4.28
[4] Biobase_2.38.0      BiocGenerics_0.24.0

loaded via a namespace (and not attached):
  [1] changepoint_2.2.2           backports_1.1.2
  [3] circlize_0.4.4              aroma.light_3.8.0
  [5] NMF_0.21.0                  plyr_1.8.4
  [7] selectr_0.4-1               ConsensusClusterPlus_1.42.0
  [9] lazyeval_0.2.1              splines_3.5.0
 [11] BiocParallel_1.12.0         GenomeInfoDb_1.14.0
 [13] ggplot2_3.0.0               gridBase_0.4-7
 [15] sva_3.26.0                  digest_0.6.17
 [17] foreach_1.4.4               magrittr_1.5
 [19] memoise_1.1.0               BSgenome_1.46.0
 [21] cluster_2.0.7-1             doParallel_1.0.11
 [23] limma_3.34.9                ComplexHeatmap_1.17.1
 [25] Biostrings_2.46.0           readr_1.1.1
 [27] annotate_1.56.2             wordcloud_2.6
 [29] matrixStats_0.54.0          R.utils_2.7.0
 [31] prettyunits_1.0.2           colorspace_1.3-2
 [33] blob_1.1.1                  rvest_0.3.2
 [35] ggrepel_0.8.0               dplyr_0.7.6
 [37] crayon_1.3.4                RCurl_1.95-4.11
 [39] jsonlite_1.5                genefilter_1.60.0
 [41] bindr_0.1.1                 survival_2.42-6
 [43] VariantAnnotation_1.24.5    zoo_1.8-3
 [45] iterators_1.0.10            glue_1.3.0
 [47] survminer_0.4.3             registry_0.5
 [49] gtable_0.2.0                zlibbioc_1.24.0
 [51] XVector_0.18.0              GetoptLong_0.1.7
 [53] DelayedArray_0.4.1          shape_1.4.4
 [55] scales_1.0.0                DESeq_1.30.0
 [57] DBI_1.0.0                   edgeR_3.20.9
 [59] rngtools_1.3.1              bibtex_0.4.2
 [61] ggthemes_4.0.1              Rcpp_0.12.18
 [63] xtable_1.8-3                progress_1.2.0
 [65] cmprsk_2.2-7                bit_1.1-14
 [67] matlab_1.0.2                mclust_5.4.1
 [69] km.ci_0.5-2                 stats4_3.5.0
 [71] httr_1.3.1                  RColorBrewer_1.1-2
 [73] pkgconfig_2.0.2             XML_3.98-1.16
 [75] R.methodsS3_1.7.1           locfit_1.5-9.1
 [77] tidyselect_0.2.4            rlang_0.2.2
 [79] reshape2_1.4.3              AnnotationDbi_1.40.0
 [81] munsell_0.5.0               tools_3.5.0
 [83] downloader_0.4              RSQLite_2.1.1
 [85] broom_0.5.0                 stringr_1.3.1
 [87] knitr_1.20                  bit64_0.9-7
 [89] survMisc_0.5.5              purrr_0.2.5
 [91] bindrcpp_0.2.2              EDASeq_2.12.0
 [93] nlme_3.1-137                R.oo_1.22.0
 [95] xml2_1.2.0                  biomaRt_2.34.2
 [97] compiler_3.5.0              curl_3.2
 [99] tibble_1.4.2                geneplotter_1.56.0
[101] stringi_1.2.4               GenomicFeatures_1.30.3
[103] lattice_0.20-35             Matrix_1.2-14
[105] KMsurv_0.1-5                pillar_1.3.0
[107] data.table_1.11.4           cowplot_0.9.3
[109] bitops_1.0-6                rtracklayer_1.38.3
[111] GenomicRanges_1.30.3        R6_2.2.2
[113] latticeExtra_0.6-28         hwriter_1.3.2
[115] RMySQL_0.10.15              ShortRead_1.36.1
[117] gridExtra_2.3               IRanges_2.12.0
[119] codetools_0.2-15            assertthat_0.2.0
[121] SummarizedExperiment_1.8.1  pkgmaker_0.27
[123] rjson_0.2.20                withr_2.1.2
[125] GenomicAlignments_1.14.2    Rsamtools_1.30.0
[127] S4Vectors_0.16.0            GenomeInfoDbData_1.0.0
[129] mgcv_1.8-24                 hms_0.4.2
[131] grid_3.5.0                  tidyr_0.8.1
[133] ggpubr_0.1.8

Please resolve my problem.
Thanks!
